name: "Danger JS"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Danger
        uses: danger/danger-js@11.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
